// <auto-generated />
using Depot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Depot.Migrations
{
    [DbContext(typeof(DataBase))]
    partial class DataBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Table", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Link = "/Room/Master",
                            Name = "Master"
                        },
                        new
                        {
                            ID = 2,
                            Link = "/Room/Average",
                            Name = "Average"
                        },
                        new
                        {
                            ID = 3,
                            Link = "/Room/Novice",
                            Name = "Novice"
                        },
                        new
                        {
                            ID = 4,
                            Link = "/Room/Beginner",
                            Name = "Beginner"
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nick")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "janek@wp.pl",
                            Name = "Jan",
                            Nick = "spacehunter",
                            Password = "password",
                            Surname = "Kowalski"
                        },
                        new
                        {
                            ID = 2,
                            Email = "kasia@wp.pl",
                            Name = "Katarzyna",
                            Nick = "darkqueen",
                            Password = "password",
                            Surname = "Ebut"
                        },
                        new
                        {
                            ID = 3,
                            Email = "zenek@wp.pl",
                            Name = "Zenon",
                            Nick = "imperator",
                            Password = "password",
                            Surname = "Dacki"
                        },
                        new
                        {
                            ID = 4,
                            Email = "seba@wp.pl",
                            Name = "Sebastian",
                            Nick = "conqueror",
                            Password = "password",
                            Surname = "Roden"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
